version: '3'

services:
  db:
    build: 
      context: ./mysql
    container_name: db
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=appdb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 3
  app:
    container_name: app
    build: 
      context: app
    entrypoint: sh -c "npm install && node index.js"
    networks:
      - app-network
    volumes:
      - ./app:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    depends_on: 
       db:
         condition: service_healthy
  nginx:
    container_name: nginx
    build: 
      context: nginx
    networks:
      - app-network
    ports:
      - "8080:80"
    depends_on: 
       - app
networks:
  app-network:
    driver: bridge