version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=appdb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app-network
  app:
    container_name: app
    build: 
      context: app
    networks:
      - app-network
    volumes:
      - ./app:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    depends_on: 
       - db
  nginx:
    container_name: nginx
    build: 
      context: nginx
    networks:
      - app-network
    ports:
      - "8080:80"      
networks:
  app-network:
    driver: bridge